spring:
  application:
    name: producer

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      enable-idempotence: true
      properties:
        spring.json.add.type.headers: false
        
    listener:
      ack-mode: manual

  cloud:
    function:
      definition: uppercase
      web:
        path: /uppercase

server:
  port: 9090
