spring:
  application:
    name: consumer

  kafka:
    consumer:
      group-id: order-group11111111
      auto-offset-reset: earliest
      enable-auto-commit: false
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.demo.consumer.RiderLocation 
    listener:
      ack-mode: manual

server:
  port: 9091
